### ISSUE TITLE
fatal error: module 'PromisesSwift' not found

### ISSUE THREAD

**Issue by maxdelia** [touchlab/KotlinCocoapods#29]
Hi, I'm trying to add [this pod](https://github.com/google/promises) to my project using the following code:
```
cocoapodsext {
        summary = "Common library for the KaMP starter kit"
        homepage = "https://github.com/touchlab/KaMPKit"
        framework {
            isStatic = false
            export(Deps.kermit)
            transitiveExport = true
        }
        pod("PromisesSwift")
    }
```
and I'm getting the following error:

```
> Task :shared:cinteropPromisesSwiftIos FAILED
Exception in thread "main" java.lang.Error: /var/folders/y7/yrztdhk977d4nh8t12ks9bkc0000gn/T/1754490655123836472.m:1:9: fatal error: module 'PromisesSwift' not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:68)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:14)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:506)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:264)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:74)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:41)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:cinteropPromisesSwiftIos'.
```
I've tried adding version, and then also module name, but nothing changed. I also get the same error adding frameworks like Alamofire or AFNetworking, I would say that I'm not able to add any pod at all. What am I doing wrong?

Ref: https://github.com/touchlab/KaMPKit/issues/192

**Comment by russhwolf** [comment]
pod dependencies only work for static frameworks. Set `isStatic = true`.

**Comment by maxdelia** [comment]
I see, thanks! Unfortunately since I was not able to use CocoaPods I switched to Swift Package Manager, so I'm not able to give You a feedback about your suggestion. I think We can close the issue!
